// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsGFD-_a39OGRXUrjP74Z4blnNuNgynM0',
    appId: '1:1032132536622:web:73208a9f4e4ac2ea2632bf',
    messagingSenderId: '1032132536622',
    projectId: 'superai-8055b',
    authDomain: 'superai-8055b.firebaseapp.com',
    storageBucket: 'superai-8055b.firebasestorage.app',
    measurementId: 'G-2K1MB04YL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPDVckHDI1gXD0uvOZK62Sd1atT_Ic28Q',
    appId: '1:1032132536622:android:0c6a063da9d044ce2632bf',
    messagingSenderId: '1032132536622',
    projectId: 'superai-8055b',
    storageBucket: 'superai-8055b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQsZ7cKF4tw-9oxgCs0fqqfgn_1d24EBQ',
    appId: '1:1032132536622:ios:31c073be840cb6202632bf',
    messagingSenderId: '1032132536622',
    projectId: 'superai-8055b',
    storageBucket: 'superai-8055b.firebasestorage.app',
    iosClientId: '1032132536622-n1ttuhrr29itcdtk36orh9859gpe8fdi.apps.googleusercontent.com',
    iosBundleId: 'my.project.myChat',
  );

}